var express = require('express')
var router = express.Router()
var skillsCtrl = require('../controllers/skills')
router.get('/', skillsCtrl.index)
router.get('/new', skillsCtrl.newSkill)
router.post('/', skillsCtrl.create)
router.get('/:id', skillsCtrl.show)
router.delete('/:id', skillsCtrl.deleteSkill)
router.get('/:id/edit', skillsCtrl.editSkill)
router.put('/:id', skillsCtrl.updateSkill)
module.exports = router
